source 'http://rubygems.org'

gem 'rspec'
gem 'capybara'
gem 'selenium-webdriver'
gem 'guard-rspec'
gem 'guard-bundler'
gem 'headless'
gem 'mime-types'
gem 'libnotify'
gem 'capybara-webkit'
gem 'pry'
gem 'poltergeist'