require 'kameleon/ext/rspec/dsl'
require 'kameleon/ext/rspec/garbage_collector'
require 'kameleon/ext/rspec/headless'
require 'kameleon/ext/rspec/pool'
require 'kameleon/ext/active_record/shared_single_connection'
